version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
    open-pull-requests-limit: 5
  - package-ecosystem: swift
    directory: "/"
    schedule:
      interval: monthly
    groups:
      swift:
        patterns: ["*"]
    open-pull-requests-limit: 5
